services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        MODE: production
    environment:
      - PYTHONPATH=/app/src:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: ["./scripts/start.sh"]
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./backend/uv.lock:/app/uv.lock:cached
      - ./backend/pyproject.toml:/app/pyproject.toml:cached
  frontend:
    container_name: frontend
    environment:
      - VITE_BACKEND_URL=https://example.com
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://example.com
        - NODE_ENV=production
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    container_name: redis
    image: redis:alpine

volumes:
      app-db-data: {}

