services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - app-db-data:/app/backend
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:alpine
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"   # SMTP
      - "1080:1080"   # Web UI
volumes:
      app-db-data: {}