"""Profile fields ctreated and cookies add

Revision ID: c56faaa235fd
Revises: 91c3f18150a3
Create Date: 2025-08-19 11:45:43.054422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56faaa235fd'
down_revision: Union[str, Sequence[str], None] = '91c3f18150a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('cookies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'cookies')
    op.drop_column('profiles', 'updated_at')
    # ### end Alembic commands ###
